### PR TITLE
retain web server

### LINKED ISSUE #12: Crash in installReceiver()
Consistently crashes when initializing HSTestingBackchannel. The web server is being deallocated when the HSTestingBackchannel initializer returns.

Screen Shot 2021-08-24 at 9 56 39 PM

Screen Shot 2021-08-24 at 10 01 53 PM

### PR DESCRIPTION
**Pull request by thompsonate**
fixes #12

### CODE REVIEW

**Comment by ConfusedVorlon** [comment]
Thanks for sorting this. Can you use a property rather than an iVar though.
cheers.

**Comment by thompsonate** [comment]
Like this? I'm not very well versed in Objective-C so there's a chance I might be doing something wrong here.

**Comment by ConfusedVorlon** [comment]
it's a while since I have done much in Obj-C as well to be honest...

you don't need the @synthesize in modern Obj-C iirc. Would you mind pulling that out? 
otherwise - that's exactly it.

**Comment by thompsonate** [comment]
Done!

**Comment by ConfusedVorlon** [comment]
thanks for sorting this.

**Pull request merged**
