### PR TITLE
Added SPM support

### PR DESCRIPTION
**Pull request by PatrikTheDev**
Added basic SPM support

### CODE REVIEW

**Comment by ConfusedVorlon** [comment]
thanks for this. 

My one thought with spm vs cocoapods is that you're stuck with the code in debug && release.

(With cocoapods - you can just add a debug-only pod.)

If we're going to add SPM support, then I think we should also have a way to remove the code at compile time in release builds. As far as I can tell, the only sensible way to do that is to wrap all the code in

```
#if !REMOVE_HS_TESTING
    // code goes here
#endif
```

with instructions added that if you're using SPM, then you can add NO_HS_TESTING to your active compilation conditions to remove the code in release builds

thoughts?

is there a better way?

**Comment by ConfusedVorlon** [comment]
also - it looks like you haven't dealt with the GCDWebServer dependency.
And that hits the same problem of including code that isn't wanted in release - but with no workaround I can think of...

**Comment by PatrikTheDev** [comment]
Another potential issue is that you can't share an SPM package across multiple targets (at least I can't seem to find a way to, if you know of anything helpful, please let me know)

Regarding your issue, I don't think there's a better solution, SPM is a lot more limited than I remembered it to be (and I didn't really want to include CocoaPods in my project just for this but it looks like it's unavoidable)

Going to close for now until we figure out a workaround for these issues

**Comment by ConfusedVorlon** [comment]
you can share SPM across multiple targets - though the UI is horrible

You add the SMP to one target, then manually add it to other targets in the 'add frameworks and libraries' section.

> Going to close for now until we figure out a workaround for these issues

I think we're waiting for SPM to evolve some...

Thanks anyway.

**Comment by PatrikTheDev** [comment]
I know you can do it that way but it doesn’t work for test targets (or at least it didn’t allow me to add it, the editor seems very unreliable)

**Comment by ConfusedVorlon** [comment]
> I know you can do it that way but it doesn’t work for test targets (or at least it didn’t allow me to add it, the editor seems very unreliable)

I hadn't spotted that. 
SPM has a way to go...

**Pull request closed without merging**
